version: '3.4'

services:
  customer.api:
    image: ${DOCKER_REGISTRY-}customerapi
    volumes:
        - testvolume:C:/volume
    build:
        context: .
        dockerfile: Customer.API\Dockerfile
    volumes:
        - testvolume:C:/volume
    networks:  
        - esnetwork


networks:
    esnetwork:
        driver: nat
volumes:
    testvolume: