version: '3.4'

services:
  customer.api:
    image: ${DOCKER_REGISTRY-}customerapi
    build:
      context: .
      dockerfile: Customer.API\Dockerfile

  gateway.api:
    image: ${DOCKER_REGISTRY-}gatewayapi
    build:
      context: .
      dockerfile: Gateway.API\Dockerfile


  orders.api:
    image: ${DOCKER_REGISTRY-}ordersapi
    build:
      context: .
      dockerfile: Orders.API\Dockerfile


  checkout.service:
    image: ${DOCKER_REGISTRY-}checkoutservice
    build:
      context: .
      dockerfile: Checkout.Service\Dockerfile


  audit.api:
    image: ${DOCKER_REGISTRY-}auditapi
    build:
      context: .
      dockerfile: Audit.API\Dockerfile

